/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenderIndexRouteImport } from './routes/tender/index'
import { Route as TenderResidensiSinaranRouteImport } from './routes/tender/residensi-sinaran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderIndexRoute = TenderIndexRouteImport.update({
  id: '/tender/',
  path: '/tender/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderResidensiSinaranRoute = TenderResidensiSinaranRouteImport.update({
  id: '/tender/residensi-sinaran',
  path: '/tender/residensi-sinaran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/tender/': typeof TenderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/tender': typeof TenderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/tender/': typeof TenderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tender/residensi-sinaran' | '/tender/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tender/residensi-sinaran' | '/tender'
  id: '__root__' | '/' | '/tender/residensi-sinaran' | '/tender/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenderResidensiSinaranRoute: typeof TenderResidensiSinaranRoute
  TenderIndexRoute: typeof TenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/': {
      id: '/tender/'
      path: '/tender'
      fullPath: '/tender/'
      preLoaderRoute: typeof TenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/residensi-sinaran': {
      id: '/tender/residensi-sinaran'
      path: '/tender/residensi-sinaran'
      fullPath: '/tender/residensi-sinaran'
      preLoaderRoute: typeof TenderResidensiSinaranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenderResidensiSinaranRoute: TenderResidensiSinaranRoute,
  TenderIndexRoute: TenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
