/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as BuyIndexRouteImport } from './routes/buy/index'
import { Route as HowETenderWorksIndexRouteImport } from './routes/how-e-tender-works/index'
import { Route as MemberIndexRouteImport } from './routes/member/index'
import { Route as OwnerAuctionIndexRouteImport } from './routes/owner-auction/index'
import { Route as OwnerAuctionResidensiSinaranRouteImport } from './routes/owner-auction/residensi-sinaran'
import { Route as RentIndexRouteImport } from './routes/rent/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as TenderIndexRouteImport } from './routes/tender/index'
import { Route as TenderResidensiSinaranRouteImport } from './routes/tender/residensi-sinaran'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowETenderWorksIndexRoute = HowETenderWorksIndexRouteImport.update({
  id: '/how-e-tender-works/',
  path: '/how-e-tender-works/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/member/',
  path: '/member/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuctionIndexRoute = OwnerAuctionIndexRouteImport.update({
  id: '/owner-auction/',
  path: '/owner-auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAuctionResidensiSinaranRoute =
  OwnerAuctionResidensiSinaranRouteImport.update({
    id: '/owner-auction/residensi-sinaran',
    path: '/owner-auction/residensi-sinaran',
    getParentRoute: () => rootRouteImport,
  } as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderIndexRoute = TenderIndexRouteImport.update({
  id: '/tender/',
  path: '/tender/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderResidensiSinaranRoute = TenderResidensiSinaranRouteImport.update({
  id: '/tender/residensi-sinaran',
  path: '/tender/residensi-sinaran',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner-auction/residensi-sinaran': typeof OwnerAuctionResidensiSinaranRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/about/': typeof AboutIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/how-e-tender-works/': typeof HowETenderWorksIndexRoute
  '/member/': typeof MemberIndexRoute
  '/owner-auction/': typeof OwnerAuctionIndexRoute
  '/rent/': typeof RentIndexRoute
  '/sell/': typeof SellIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tender/': typeof TenderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner-auction/residensi-sinaran': typeof OwnerAuctionResidensiSinaranRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/about': typeof AboutIndexRoute
  '/buy': typeof BuyIndexRoute
  '/how-e-tender-works': typeof HowETenderWorksIndexRoute
  '/member': typeof MemberIndexRoute
  '/owner-auction': typeof OwnerAuctionIndexRoute
  '/rent': typeof RentIndexRoute
  '/sell': typeof SellIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tender': typeof TenderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner-auction/residensi-sinaran': typeof OwnerAuctionResidensiSinaranRoute
  '/tender/residensi-sinaran': typeof TenderResidensiSinaranRoute
  '/about/': typeof AboutIndexRoute
  '/buy/': typeof BuyIndexRoute
  '/how-e-tender-works/': typeof HowETenderWorksIndexRoute
  '/member/': typeof MemberIndexRoute
  '/owner-auction/': typeof OwnerAuctionIndexRoute
  '/rent/': typeof RentIndexRoute
  '/sell/': typeof SellIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tender/': typeof TenderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner-auction/residensi-sinaran'
    | '/tender/residensi-sinaran'
    | '/about/'
    | '/buy/'
    | '/how-e-tender-works/'
    | '/member/'
    | '/owner-auction/'
    | '/rent/'
    | '/sell/'
    | '/services/'
    | '/tender/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner-auction/residensi-sinaran'
    | '/tender/residensi-sinaran'
    | '/about'
    | '/buy'
    | '/how-e-tender-works'
    | '/member'
    | '/owner-auction'
    | '/rent'
    | '/sell'
    | '/services'
    | '/tender'
  id:
    | '__root__'
    | '/'
    | '/owner-auction/residensi-sinaran'
    | '/tender/residensi-sinaran'
    | '/about/'
    | '/buy/'
    | '/how-e-tender-works/'
    | '/member/'
    | '/owner-auction/'
    | '/rent/'
    | '/sell/'
    | '/services/'
    | '/tender/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerAuctionResidensiSinaranRoute: typeof OwnerAuctionResidensiSinaranRoute
  TenderResidensiSinaranRoute: typeof TenderResidensiSinaranRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BuyIndexRoute: typeof BuyIndexRoute
  HowETenderWorksIndexRoute: typeof HowETenderWorksIndexRoute
  MemberIndexRoute: typeof MemberIndexRoute
  OwnerAuctionIndexRoute: typeof OwnerAuctionIndexRoute
  RentIndexRoute: typeof RentIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TenderIndexRoute: typeof TenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-e-tender-works/': {
      id: '/how-e-tender-works/'
      path: '/how-e-tender-works'
      fullPath: '/how-e-tender-works/'
      preLoaderRoute: typeof HowETenderWorksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-auction/': {
      id: '/owner-auction/'
      path: '/owner-auction'
      fullPath: '/owner-auction/'
      preLoaderRoute: typeof OwnerAuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-auction/residensi-sinaran': {
      id: '/owner-auction/residensi-sinaran'
      path: '/owner-auction/residensi-sinaran'
      fullPath: '/owner-auction/residensi-sinaran'
      preLoaderRoute: typeof OwnerAuctionResidensiSinaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/': {
      id: '/tender/'
      path: '/tender'
      fullPath: '/tender/'
      preLoaderRoute: typeof TenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender/residensi-sinaran': {
      id: '/tender/residensi-sinaran'
      path: '/tender/residensi-sinaran'
      fullPath: '/tender/residensi-sinaran'
      preLoaderRoute: typeof TenderResidensiSinaranRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerAuctionResidensiSinaranRoute: OwnerAuctionResidensiSinaranRoute,
  TenderResidensiSinaranRoute: TenderResidensiSinaranRoute,
  AboutIndexRoute: AboutIndexRoute,
  BuyIndexRoute: BuyIndexRoute,
  HowETenderWorksIndexRoute: HowETenderWorksIndexRoute,
  MemberIndexRoute: MemberIndexRoute,
  OwnerAuctionIndexRoute: OwnerAuctionIndexRoute,
  RentIndexRoute: RentIndexRoute,
  SellIndexRoute: SellIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TenderIndexRoute: TenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
